"""

New Utility: Flattened CSV Exporter (src/exporter.py)This script takes the multi-modal nested JSON configurations generated by your annotation pipeline and flattens them into a clean, uniform tabular .csv table that can be read directly by spreadsheet tools or simple tabular networks.
"""


import os
import pandas as pd

class CSVExporter:
    @staticmethod
    def convert_manifest_to_csv(master_manifest, output_directory):
        """
        Parses multi-modal hierarchical dictionaries and exports a single 
        flattened, structured CSV data ledger file.
        """
        flattened_rows = []
        
        for asset_name, details in master_manifest.items():
            if "error" in details or "modality" not in details:
                continue
                
            # Flatten metrics into standard key-value pairs
            row_entry = {
                "Asset_Name": asset_name,
                "Engineering_Modality": details.get("modality", "N/A"),
                "Assigned_AI_Label": details.get("assigned_label", "N/A")
            }
            
            # Unpack domain-specific numeric calculations safely
            metrics = details.get("metrics", {})
            for metric_key, value in metrics.items():
                if isinstance(value, list):
                    row_entry[metric_key] = "|".join(map(str, value))
                elif isinstance(value, dict):
                    for sub_key, sub_val in value.items():
                        row_entry[f"{metric_key}_{sub_key}"] = sub_val
                else:
                    row_entry[metric_key] = value
                    
            flattened_rows.append(row_entry)
            
        if flattened_rows:
            df = pd.DataFrame(flattened_rows)
            csv_path = os.path.join(output_directory, "tabular_engineering_dataset.csv")
            df.to_csv(csv_path, index=False)
            print(f"📊 Tabular database compiled successfully: {csv_path}")
